### ISSUE TITLE
Automated basic biothings web functionality test for data applications

### ISSUE THREAD

**Issue by namespacestd0** [biothings/biothings.api#107]
Now that we have automated tests to run after each app (mygene, myvariant, ...) build under development, explore the possibility to run an automated basic biothings functionality test to ensure in addition to the customizations working, the basic features are also not affected.

**Comment by zcqian** [comment]
So the tests should belong to BioThings, but testing against customized versions?

**Comment by namespacestd0** [comment]
yes

**Comment by namespacestd0** [comment]
Additionally, data tests are deployed with details at https://github.com/biothings/biothings-internal/wiki/Data-Integrity-Checker (Internal Link). The originally described functionalities are assigned to @zcqian.

**Comment by namespacestd0** [comment]
@zcqian please also test that documentations can build without error

**Comment by zcqian** [comment]
Are we interested in just making sure they build from the command line, or do we want to use the buildthedocs container which is actually somewhat harder to do but more accurately represents the actual documentation build environment?

**Comment by newgene** [comment]
@zcqian I think just the sphinx build with our own `conf.py` in this repo is good enough.

Or I even think we don't need to test it on our own, because readthedocs build is automatically triggered and we do have a badge in our README to show the build status: 

[![Documentation Status](https://readthedocs.org/projects/biothingsapi/badge/?version=latest)](https://docs.biothings.io/en/latest/?badge=latest)

The only downside is we won't be notified when the build fails (maybe there is a way to enable it at readthedocs).

**Comment by namespacestd0** [comment]
Oh then let's rely on the automatic check.

**Comment by zcqian** [comment]
Unless we’re modifying docs we shouldn’t expect doc building to fail when the package can build. Last time it actually broke the package building, that’s why docs weren’t getting built

**Comment by zcqian** [comment]
Implemented in various API projects.

Caveat: MV Beacon API only tests for the endpoint presence, (i.e., the handers are registered to the proper routes), it does not actually test that the Beacon API is behaving correctly.
