### ISSUE TITLE
Implement full release installation without downtime

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#134]
Currently from the biothings hub and studio, we can install incremental releases directly with no downtime (applying diffs on the production index).  The relevant code is here:

https://github.com/biothings/biothings.api/blob/1b96f0aded05873d642134c0c38b15fa982e3b6d/biothings/hub/standalone/__init__.py#L68

In the case of deploying a full release, we currently have two options:

1. delete the old index and then install the new index (restoring snapshots)
    This causes downtime, but it's brief for small data indices.

2. we perform a manual index restoration to a different index name and then switch the alias when it's done.
    This has no downtime, should be preferred. 

We should implement these manual steps from the `#2` option as a feature in biothings hub/studio.

**Comment by zcqian** [comment]
This is currently being worked on (for a while), and this comment is to document some implications of the planned changes.

The actual code responsible for the full release is located at `biothings.hub.autoupdate.uploader.BiothingsUploader` in the `update_data` coroutine (thanks to @namespacestd0 ) for pointing it out.

For full release it then calls the `restore_snapshot` coroutine, which in turn, calls the `restore` method in `biothings.utils.es.ESIndexer`. `ESIndexer` more or less is a wrapper for the official Elasticsearch Python library.

By replacing the target index with an alias, `ESIndexer` is more or less capable of handling such situations. However, it tends to resolve the index name before storing it in its protected property `_index`. Also, the `wrapper` decorator in `biothings.utils.es` is given the ability to modify the the `_index` (and `doc_type`) properties of `ESIndexer` when any of the decorated methods are called, which further complicates the situation.

Is there any assumptions that we can make regarding the target index/alias name? I am proposing that we:
 - store the original index name in a public instance variable
 - add a `restore_and_alias` method which restores the index to a random name and creates/updates the alias (with the original index name)

There are potential issues with this approach due to the complex behavior regarding the `_index` property.

**Comment by zcqian** [comment]
Currently WIP

In this branch, https://github.com/biothings/biothings.api/tree/add_full_release_install_alias_swap in class `ESIndexer` from `biothings.utils.es`, two methods have been added, `restore_and_alias` and `update_alias`. This is to open up a discussion on which would be the better interface design. `restore_and_alias` is almost a drop in replacement for `restore`, while `update_alias` needs to be used in conjunction with `restore` and it also involves swapping the `_index` instance variable which is not yet implemented.

More details will be added later.

**Comment by zcqian** [comment]
I think it is okay to assume that leaving `_index` out of sync won't cause too many problems, if we only consider the `ESIndexer` in `BiothingsUploader` -- given that during the meeting it was believed that for any other uses they are frequently re-initialized/created or don't operate on the same index so `_index` being stales is a none issue.

When installation is triggered, "concrete" `BiothingsUploader` sub-classes are always (freshly) initialized from the `UploaderManager`.

In `biothings.hub.standalone.__init__.AutoHubFeature.configure`, we can see that during the dynamical creation of sub-classes of the Uploader, a callable (partial) that returns a new `DocESBackend` is always used as `TARGET_BACKEND`.

`DocESBackend` takes `pidxr` as an argument to set its `target_esidxer`. In `AutoHubFeature` when `indexer_factory` is not used, `pidxr` is a partial that initializes a new `ESIndexer`. When `indexer_factory` is used, at least in `DynamicIndexerFactory` it also returns a callable that will return a new `ESIndexer`.

Therefore, for every restore operation, `ESIndexer` is always new and we do not have to worry about `_index` being stale.

**Comment by zcqian** [comment]
It's been changed so that `ESIndexer`:
- has one new attribute `canonical_index_name` which refers to the index name used to initialize the object
- has a new method `get_alias` to list indices associated with an alias
- has a new method `update_alias` to create or update an alias, or overwrite an index with an alias
- method `delete_index` now takes optional `index` parameter so that it can delete other indices

I'm still not sure if this is the best design but so far this branch does what it says, and performs seamless migration from the old behavior.

**Comment by namespacestd0** [comment]
I think it's also very useful for the new index to have the same replication settings as the original one it is replacing. @zcqian please see how this can be implemented.

**Comment by newgene** [comment]
Good point about replica settings. What we did previously manually is like this:
* set `replica=0`
* deploy index
* assign alias
* test
* delete old index
* set `replica` to the original value (e.g. 1)
