### ISSUE TITLE
build time does not display correctly

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#248]
`Build time: 0-21h14m05s` is incorrect:

<img width="255" alt="image" src="https://user-images.githubusercontent.com/130158/181384611-e0926846-6688-4648-b80a-978c3e535cb8.png">

Looks like the time values are incorrect for three snapshot "steps":
(from /mytaxon/builds?conf_name=mytaxonomy from mytaxon_hub)

<img width="534" alt="image" src="https://user-images.githubusercontent.com/130158/181384761-a741bbb3-e91a-42ae-a484-7ceaf12a8e11.png">

Suspect this is related to the timezone information (maybe missing tz in the snapshot timestamps?)

**Comment by everaldorodrigo** [comment]
Just to have it documented here:

1. Calling http://su05:11080/builds 

2. The response has negative values. Ex: ```"time_in_s": -25200, "time": "-6h0.03s",```. We can see it in the print below:
<img width="503" alt="image" src="https://user-images.githubusercontent.com/5834247/181412351-2650d0d9-b855-4f45-9ed0-35a847b31cbe.png">

3. The source code related with the negative values:
https://github.com/biothings/biothings.api/blob/b6d9380794259846eda512a3fb1eae4ba20632b5/biothings/hub/dataindex/snapshot_registrar.py#L68

4. The start date ```step_started_at``` comes from here. Maybe we can find some problem here:
https://github.com/biothings/biothings.api/blob/b6d9380794259846eda512a3fb1eae4ba20632b5/biothings/hub/dataindex/snapshot_registrar.py#L50

To be continued...

**Comment by everaldorodrigo** [comment]
New `pymongo` lib version changed the default configuration value of `tz_aware` to `False` instead of `True`.

Because of that the datetime value read from mongodb was not including the timezone anymore.

The solution is forcing the datetime value to include the UTC timezone when it is missing.

Reference: https://pymongo.readthedocs.io/en/stable/migrate-to-pymongo4.html?highlight=datetime#tz-aware-defaults-to-false

Evidence: 
![image](https://user-images.githubusercontent.com/5834247/181861069-5a1ea7a6-dcae-4c69-90c0-5e2bc66d71a9.png)
