### ISSUE TITLE
Responsive web inerface

### ISSUE THREAD

**Issue by dongbohu** [biothings/biothings.api#91]
When I used Google Chrome to launch the biothings-studio web interface on my laptop, I found that some icons on the right side were hidden because my laptop's screen size is not big enough:
<img width="1347" alt="partial" src="https://user-images.githubusercontent.com/15133253/96723258-5487f200-137c-11eb-8bb5-984a542e1f0d.png">

I have to maximize Google Chrome's window to full screen in order to access the hidden icons on the web UI:
<img width="1437" alt="full" src="https://user-images.githubusercontent.com/15133253/96723513-a466b900-137c-11eb-8020-5073536f9827.png">

It will be nice to make the web UI responsive, such as adding a scrollbar when the browser's screen can't show all widgets.

**Comment by juliamullen** [comment]
Hi! Instead of adding a scrollbar I've moved some of the job indicators to the bottom menu bar. This should work for most laptop widths, although may still not be sufficient for e.g., tablet or half-screens sizes. Other responsive changes are being considered to maximize usability for smaller window sizes. When the PR moves to master I'll close this issue.
